### ISSUE TITLE
Install on etherpad-lite 1.5.5

### ISSUE THREAD

**Issue by ternite** [tykeal/ep_ldapauth#21]
When downloading etherpad-lite 1.5.5 (Win), then installing the included ep_lpapauth 0.2.0 via /admin/plugins, the install process ruins the etherpad installation.

A popup with an OK button and the following text appears during installation:
"An error occured while installing ep_ldapauth 
buffertools@1.1.0 install: `node-gyp rebuild`
Exit status 1"

After that, etherpad won't work properly anymore.

Best regards
ternite

**Comment by stefanschauer** [comment]
I have the same problem.
I followed this instructions: http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm 
but still I am not able to install the plugin.
and still get this error 
"An error occured while installing ep_ldapauth
buffertools@1.1.0 install: node-gyp rebuild
Exit status 1"

if I try to install via the command line I get this error 
npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/storage/etherpad/npm-debug.log

any hints how to install the plugin?

best

**Comment by magnus919** [comment]
I can also reproduce the problem.

**Comment by vinzent** [comment]
> npm ERR! This is most likely a problem with the buffertools package,

you should check if buffertools does support windows. this is not an ep_ldapauth problem.

maybe related: https://github.com/bnoordhuis/node-buffertools/issues/21

**Comment by ArthurHlt** [comment]
I have the same issue on linux environment but i feel likes it's more a problem from buffertools and node 0.12

**Comment by BlackyFox** [comment]
I have the same issue on a Debian 7

**Comment by froiloc** [comment]
What I did was to install everything from git only. Please check out my solution:
https://github.com/tykeal/ep_ldapauth/issues/25#issuecomment-115354806

**Comment by Kirotay** [comment]
I just install the following packages.

apt-get install build-essential g++

**Comment by tykeal** [comment]
This should be resolved with the new v0.3.0 module that was just released.
