### ISSUE TITLE
I got an error installing on etherpad lite 1.5.6

### ISSUE THREAD

**Issue by bodypheo** [tykeal/ep_ldapauth#25]
Hello I ve tried to install it on an etherpad install and after running npm install  ep_ldapauth I got this error:
Any idea what could be? I am not very used to npm.
Thanks

npm ERR! Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ep_ldapauth"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/etherpad-lite/npm-debug.log

**Comment by Kirotay** [comment]
I also get an error message.

A more detailed error message:

make: Entering directory `/var/www/etherpad-lite/node_modules/ep_ldapauth/node_modules/ldapjs/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
../buffertools.cc:19:52: error: ‘Arguments’ does not name a type
../buffertools.cc:19:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:21:33: error: ‘Arguments’ does not name a type
../buffertools.cc:21:44: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::UnaryAction<Derived>::operator()(const int&)’:
../buffertools.cc:24:29: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
../buffertools.cc:26:47: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:27:45: error: there are no arguments to ‘ThrowException’ that depend on a template parameter, so a declaration of ‘ThrowException’ must be available [-fpermissive]
../buffertools.cc:27:45: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../buffertools.cc: At global scope:
../buffertools.cc:35:86: error: ‘Arguments’ does not name a type
../buffertools.cc:35:97: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:37:33: error: ‘Arguments’ does not name a type
../buffertools.cc:37:44: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::BinaryAction<Derived>::operator()(const int&)’:
../buffertools.cc:40:29: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
../buffertools.cc:42:47: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:43:45: error: there are no arguments to ‘ThrowException’ that depend on a template parameter, so a declaration of ‘ThrowException’ must be available [-fpermissive]
../buffertools.cc:46:13: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:47:30: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:50:33: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:51:32: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:56:80: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:58:70: error: no matching function for call to ‘v8::Exception::TypeError(v8::Persistent<v8::String>&)’
../buffertools.cc:58:70: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3946:23: note: static v8::Local<v8::Value> v8::Exception::TypeError(v8::Handle<v8::String>)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3946:23: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Handle<v8::String>’
../buffertools.cc:58:71: error: there are no arguments to ‘ThrowException’ that depend on a template parameter, so a declaration of ‘ThrowException’ must be available [-fpermissive]
../buffertools.cc: At global scope:
../buffertools.cc:104:52: error: ‘Arguments’ does not name a type
../buffertools.cc:104:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:110:52: error: ‘Arguments’ does not name a type
../buffertools.cc:110:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::FillAction::apply(v8::Handle<v8::Object>&, const int&, v8::HandleScope&)’:
../buffertools.cc:111:13: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:112:18: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:116:13: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:117:30: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:121:33: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:122:33: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:128:80: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:130:70: error: no matching function for call to ‘v8::Exception::TypeError(v8::Persistent<v8::String>&)’
../buffertools.cc:130:70: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3946:23: note: static v8::Local<v8::Value> v8::Exception::TypeError(v8::Handle<v8::String>)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3946:23: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Handle<v8::String>’
../buffertools.cc:130:71: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc: At global scope:
../buffertools.cc:137:52: error: ‘Arguments’ does not name a type
../buffertools.cc:137:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:149:86: error: ‘Arguments’ does not name a type
../buffertools.cc:149:97: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::EqualsAction::apply(v8::Handle<v8::Object>&, const uint8_t*, size_t, const int&, v8::HandleScope&)’:
../buffertools.cc:150:50: error: too few arguments to function ‘v8::Handle<v8::Boolean> v8::True(v8::Isolate*)’
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:6613:17: note: declared here
../buffertools.cc:150:60: error: too few arguments to function ‘v8::Handle<v8::Boolean> v8::False(v8::Isolate*)’
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:6622:17: note: declared here
../buffertools.cc: At global scope:
../buffertools.cc:155:86: error: ‘Arguments’ does not name a type
../buffertools.cc:155:97: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::CompareAction::apply(v8::Handle<v8::Object>&, const uint8_t*, size_t, const int&, v8::HandleScope&)’:
../buffertools.cc:156:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
../buffertools.cc:156:62: error: no matching function for call to ‘v8::Integer::New(int)’
../buffertools.cc:156:62: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../buffertools.cc: At global scope:
../buffertools.cc:161:88: error: ‘Arguments’ does not name a type
../buffertools.cc:161:99: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::IndexOfAction::apply(v8::Handle<v8::Object>&, const uint8_t*, size_t, const int&, v8::HandleScope&)’:
../buffertools.cc:165:25: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:176:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
../buffertools.cc:176:41: error: no matching function for call to ‘v8::Integer::New(const ptrdiff_t&)’
../buffertools.cc:176:41: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../buffertools.cc: At global scope:
../buffertools.cc:194:84: error: ‘Arguments’ does not name a type
../buffertools.cc:194:95: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In function ‘v8::Handle<v8::Value> {anonymous}::decodeHex(const uint8_t*, size_t, const int&, v8::HandleScope&)’:
../buffertools.cc:196:42: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:197:57: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc:201:24: error: no matching function for call to ‘v8::String::Empty()’
../buffertools.cc:201:24: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:6236:15: note: static v8::Local<v8::String> v8::String::Empty(v8::Isolate*)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:6236:15: note:   candidate expects 1 argument, 0 provided
../buffertools.cc:204:50: error: ‘class v8::Object’ has no member named ‘handle_’
../buffertools.cc:214:43: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:215:39: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc: At global scope:
../buffertools.cc:225:52: error: ‘Arguments’ does not name a type
../buffertools.cc:225:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:233:52: error: ‘Arguments’ does not name a type
../buffertools.cc:233:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc: In member function ‘v8::Handle<v8::Value> {anonymous}::ToHexAction::apply(v8::Handle<v8::Object>&, const int&, v8::HandleScope&)’:
../buffertools.cc:238:25: error: no matching function for call to ‘v8::String::Empty()’
../buffertools.cc:238:25: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:6236:15: note: static v8::Local<v8::String> v8::String::Empty(v8::Isolate*)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:6236:15: note:   candidate expects 1 argument, 0 provided
../buffertools.cc:248:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
../buffertools.cc:248:22: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc: At global scope:
../buffertools.cc:255:27: error: ‘Arguments’ does not name a type
../buffertools.cc:255:38: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:259:26: error: ‘Arguments’ does not name a type
../buffertools.cc:259:37: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:263:29: error: ‘Arguments’ does not name a type
../buffertools.cc:263:40: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:267:28: error: ‘Arguments’ does not name a type
../buffertools.cc:267:39: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:271:29: error: ‘Arguments’ does not name a type
../buffertools.cc:271:40: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:275:29: error: ‘Arguments’ does not name a type
../buffertools.cc:275:40: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:279:29: error: ‘Arguments’ does not name a type
../buffertools.cc:279:40: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:283:27: error: ‘Arguments’ does not name a type
../buffertools.cc:283:38: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../buffertools.cc:287:28: error: ‘Arguments’ does not name a type
../buffertools.cc:287:39: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> {anonymous}::Concat(const int&)’:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:288:14: error: within this context
../buffertools.cc:291:36: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../buffertools.cc:292:32: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:305:8: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:305:37: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc:309:8: error: expected primary-expression before ‘&’ token
../buffertools.cc:309:10: error: ‘dst’ was not declared in this scope
../buffertools.cc:312:36: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../buffertools.cc:313:32: error: invalid types ‘const int[int]’ for array subscript
../buffertools.cc:327:43: error: ‘New’ is not a member of ‘v8::String’
../buffertools.cc:329:61: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc:333:15: error: ‘class v8::HandleScope’ has no member named ‘Close’
../buffertools.cc: In function ‘void {anonymous}::RegisterModule(v8::Handle<v8::Object>)’:
../buffertools.cc:337:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:337:72: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:337:72: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:338:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:338:70: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:338:70: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:339:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:339:71: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:339:71: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:340:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:340:73: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:340:73: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:341:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:341:72: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:341:72: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:342:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:342:73: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:342:73: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:343:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:343:73: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:343:73: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:344:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:344:73: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:344:73: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc:345:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
../buffertools.cc:345:71: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
../buffertools.cc:345:71: note: candidate is:
In file included from ../buffertools.cc:1:0:
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::UnaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::ClearAction]’:
../buffertools.cc:256:27:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:22:15: error: within this context
../buffertools.cc:27:45: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::UnaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::FillAction]’:
../buffertools.cc:260:26:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:22:15: error: within this context
../buffertools.cc:27:45: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::UnaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::ReverseAction]’:
../buffertools.cc:264:29:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:22:15: error: within this context
../buffertools.cc:27:45: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::BinaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::EqualsAction]’:
../buffertools.cc:268:28:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:38:15: error: within this context
../buffertools.cc:43:45: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc:58:71: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::BinaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::CompareAction]’:
../buffertools.cc:272:29:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:38:15: error: within this context
../buffertools.cc:43:45: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc:58:71: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::BinaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::IndexOfAction]’:
../buffertools.cc:276:29:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:38:15: error: within this context
../buffertools.cc:43:45: error: ‘ThrowException’ was not declared in this scope
../buffertools.cc:58:71: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::UnaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::FromHexAction]’:
../buffertools.cc:280:29:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:22:15: error: within this context
../buffertools.cc:27:45: error: ‘ThrowException’ was not declared in this scope
In file included from ../buffertools.cc:1:0:
../buffertools.cc: In instantiation of ‘v8::Handle<v8::Value> {anonymous}::UnaryAction<Derived>::operator()(const int&) [with Derived = {anonymous}::ToHexAction]’:
../buffertools.cc:284:27:   required from here
/root/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../buffertools.cc:22:15: error: within this context
../buffertools.cc:27:45: error: ‘ThrowException’ was not declared in this scope

**Comment by froiloc** [comment]
I got the same issue, when I installed this plugin using command line

npm install ep_ldapauth

or installing it using the admin/plugin interface

Nevertheless I made it running and working. :) Here is what I did.
Make sure you have git installed.

got to the folder where you installed etherpad-lite
cd node_modules
git clone https://github.com/tykeal/ep_ldapauth   ep_ldapauth
mkdir ep_ldapauth/node_modules
git clone https://github.com/mcavage/node-ldapjs   ep_ldapauth/node_modules/ldapjs
git clone https://github.com/Pita/async-stacktrace   ep_ldapauth/node_modules/async-stacktrace
mkdir ep_ldapauth/node_modules/ldapjs/node_modules
git clone https://github.com/mcavage/node-asn1 ep_ldapauth/node_modules/ldapjs/node_modules/asn1
git clone https://github.com/mcavage/node-assert-plus ep_ldapauth/node_modules/ldapjs/node_modules/assert-plus
git clone https://github.com/trentm/node-bunyan ep_ldapauth/node_modules/ldapjs/node_modules/bunyan
git clone https://github.com/trentm/node-dashdash ep_ldapauth/node_modules/ldapjs/node_modules/dashdash
git clone https://github.com/MathieuTurcotte/node-backoff ep_ldapauth/node_modules/ldapjs/node_modules/backoff
git clone https://github.com/pfmooney/node-ldap-filter ep_ldapauth/node_modules/ldapjs/node_modules/ldap-filter
git clone https://github.com/isaacs/once ep_ldapauth/node_modules/ldapjs/node_modules/once
git clone https://github.com/davepacheco/node-vasync  ep_ldapauth/node_modules/ldapjs/node_modules/vasync
git clone https://github.com/davepacheco/node-verror ep_ldapauth/node_modules/ldapjs/node_modules/verror
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/backoff/node_modules
git clone https://github.com/MathieuTurcotte/node-precond ep_ldapauth/node_modules/ldapjs/node_modules/backoff/node_modules/precond
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/dashdash/node_modules
git clone https://github.com/mcavage/node-assert-plus ep_ldapauth/node_modules/ldapjs/node_modules/dashdash/node_modules/assert-plus
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/ldap-filter/node_modules
git clone https://github.com/mcavage/node-assert-plus ep_ldapauth/node_modules/ldapjs/node_modules/ldap-filter/node_modules/assert-plus
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/once/node_modules
git clone https://github.com/npm/wrappy ep_ldapauth/node_modules/ldapjs/node_modules/once/node_modules/wrappy
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/vasync/node_modules
git clone https://github.com/davepacheco/node-verror ep_ldapauth/node_modules/ldapjs/node_modules/vasync/node_modules/verror
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/vasync/node_modules/verror/node_modules
git clone https://github.com/davepacheco/node-extsprintf ep_ldapauth/node_modules/ldapjs/node_modules/vasync/node_modules/verror/node_modules/extsprintf
mkdir ep_ldapauth/node_modules/ldapjs/node_modules/verror/node_modules
git clone https://github.com/davepacheco/node-extsprintf ep_ldapauth/node_modules/ldapjs/node_modules/verror/node_modules/extsprintf

Maybe you need to adjust the user access rights to the files afterwards. With me it was

chown -R etherpad:etherpad .

Then just restart the etherpad-server and it should work.

bin/run.sh

I hope that helps. :)

**Comment by tykeal** [comment]
@froiloc since it sounds like the dependencies just need to be updated, if you could submit a patch that updates the dependencies appropriately I would be more than happy to merge it. Heck, I'll likely bump the version and release a new package if you do (provided I can remember how to ;) )

**Comment by froiloc** [comment]
@tykeal 
Hi, the problem are not the dependecies of your ep_ldapauth project. It's the dependencies of the modules your project uses. So I'm not quite sure a patch of your project would make any difference. :(

I'm afraid the only feasible solution right now is to install the ldapjs in the manner I proposed. Until ldapjs is repacked properly for the usage with npm.

Sorry, that I cannot be of any help in this matter.

**Comment by tykeal** [comment]
Ah, I didn't realize that. As I've mentioned, I don't really work much on this as it isn't a high priority to me, part of the reason this is on GitHub, I hope / expect folks that care to actually contribute some because, frankly I don't care enough outside of, is it secure, and does it deal with my use case ;)

**Comment by dvorak** [comment]
The latest ldapjs release (0.7.1) will install,but doesn't work.  My work around was to do the following:

    npm install https://github.com/tykeal/ep_ldapauth.git\#ecf6e5490ea2e22e59cc70d18879c5a7942ce6a1
    cd node_modules/ep_ldapauth
    npm install https://github.com/mcavage/node-ldapjs.git\#acc1ca8f4314fd9d67561feabc8ce4c235076a5e

**Comment by tykeal** [comment]
This should be resolved with the latest release of the module (v0.3.0)
