### ISSUE TITLE
node-gyp rebuild error while installing the plugin

### ISSUE THREAD

**Issue by varwiz** [tykeal/ep_ldapauth#30]
i get the below error,

> node-gyp rebuild

make: Entering directory `/home/vardha/etherpad-lite/node_modules/ep_ldapauth/node_modules/ldapjs/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory`/home/vardha/etherpad-lite/node_modules/ep_ldapauth/node_modules/ldapjs/node_modules/dtrace-provider/build'
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "ep_ldapauth"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vardha/etherpad-lite/npm-debug.log

any idea as to why?

**Comment by tykeal** [comment]
I have finally released v0.3.0 of the module. I suggest you upgrade as the version of ldapjs that was being used was way out of date and had problems with current installs.

**Comment by varwiz** [comment]
thank you. the new build installs just fine :)
